# Generated by Django 2.2.5 on 2020-11-16 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name_teams',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='division_name_teams', to='teams.Team'),
        ),
    ]
